Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: MovieDataLoader
Resources:  
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration: 
        Status: Enabled

Outputs:
    BucketName:
      Value: !Ref S3Bucket
      Description: S3 Bucket for storing function package(s)
      Export: 
        Name: !Sub ${EnvironmentName}:coreinf-functionbucket