Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: CovidDataLoader
  MyEmail :
    Type: String
    Description: Email for notifications
    AllowedPattern: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$"
    ConstraintDescription: You should enter a valid email
Resources:
  MySubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref MyEmail
      Protocol: email
      TopicArn: 
        Fn::ImportValue: !Sub ${EnvironmentName}:SNSTopic